modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/oneachina/OpzeUI-NeoForge/issue" #optional
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://github.com/oneachina/OpzeUI-NeoForge"
#logoFile="examplemod.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''
